### ISSUE TITLE
KeyError: 'sms'

### ISSUE THREAD

**Issue by travisghansen** [apostvav/kannel_exporter#8]
I get the following failure.  Not sure if it's because I run kannel `1.5.0` or something else.

```
Traceback (most recent call last):
  File "/usr/local/bin/kannel_exporter.py", line 385, in <module>
    main()
  File "/usr/local/bin/kannel_exporter.py", line 377, in main
    REGISTRY.register(KannelCollector(args.target, status_password, opts))
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 24, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.7/site-packages/prometheus_client/registry.py", line 64, in _get_names
    for metric in desc_func():
  File "/usr/local/bin/kannel_exporter.py", line 282, in collect
    smsc_stats_by_id[smscid]['sms']['received'] = int(smsc['sms']['received'])
KeyError: 'sms'
```

Here is the XML dataset:

```
<?xml version="1.0"?>
<gateway>
<version>Kannel bearerbox version `1.5.0'.
Build `Nov  4 2017 20:37:11', compiler `4.8.5 20150623 (Red Hat 4.8.5-16)'.
System Linux, release 3.10.0-957.5.1.el7.x86_64, version #1 SMP Fri Feb 1 14:54:57 UTC 2019, machine x86_64.
Hostname kannel-0.kannel-headless.namespace.svc.cluster.local, IP 10.42.4.130.
Libxml version 2.9.1.
Using OpenSSL 1.0.2k-fips  26 Jan 2017.
Compiled with MySQL 5.5.56-MariaDB, using MySQL 5.5.56-MariaDB.
Using SQLite 3.7.17.
Using native malloc.
</version>
<status>running, uptime 0d 0h 0m 15s</status>
	<wdp>
		<received><total>0</total><queued>0</queued></received>
		<sent><total>0</total><queued>0</queued></sent>
	</wdp>
	<sms>
		<received><total>0</total><queued>0</queued></received>
		<sent><total>0</total><queued>0</queued></sent>
		<storesize>0</storesize>
		<inbound>0.00,0.00,0.00</inbound>
		<outbound>0.00,0.00,0.00</outbound>
		</sms>
	<dlr>
		<received><total>0</total></received>
		<sent><total>0</total></sent>
		<inbound>0.00,0.00,0.00</inbound>
		<outbound>0.00,0.00,0.00</outbound>
		<queued>-1</queued>
		<storage>mysql</storage>
	</dlr>
<boxes>
	<box>
		<type>smsbox</type>
		<id>sqlbox</id>
		<IP>127.0.0.1</IP>
		<queue>0</queue>
		<status>on-line 0d 0h 0m 15s</status>
		<ssl>no</ssl>
	</box><box>
		<type>smsbox</type>
		<id></id>
		<IP>127.0.0.1</IP>
		<queue>0</queue>
		<status>on-line 0d 0h 0m 5s</status>
		<ssl>no</ssl>
	</box></boxes>
<smscs><count>1</count>
	<smsc>
		<name>HTTP:generic</name>
		<admin-id>twilio</admin-id>
		<id>twilio</id>
		<status>online 15s</status>
		<received><sms>0</sms><dlr>0</dlr></received>
		<sent><sms>0</sms><dlr>0</dlr></sent>
		<failed>0</failed>
		<queued>0</queued>
	</smsc>
</smscs>
</gateway>
```

**Comment by apostvav** [comment]
Hi,

Yes, it has to do with the 1.5.0 version status format.

SMSC metrics used to be like that:
```
<smsc>
	<name>FAKE:20001</name>
	<admin-id>fakesmsc</admin-id>
	<id>fakesmsc</id>
	<status>online 3176s</status>
	<failed>0</failed>
	<queued>0</queued>
	<sms>
		<received>0</received>
		<sent>3</sent>
		<inbound>0.00,0.00,0.00</inbound>
		<outbound>0.01,0.00,0.00</outbound>
	</sms>
	<dlr>
		<received>6</received>
		<sent>0</sent>
		<inbound>0.02,0.00,0.00</inbound>
		<outbound>0.00,0.00,0.00</outbound>
	</dlr>
</smsc>
```

I added an if clause so both formats can be parsed.
Please test and let me know if you have any issues.

**Comment by travisghansen** [comment]
I've been using the docker images...is there an tag with the development code I can use?

**Comment by apostvav** [comment]
I've just uploaded it on docker hub. The tag is 0.3.1

**Comment by travisghansen** [comment]
@apostvav beautiful, thanks for the quick update! So far works like a charm now (haven't validated the data or anything). If I see any crashes or anything else I'll open another ticket.

**Comment by travisghansen** [comment]
By chance are using it with grafana and have a dashboard made?

**Comment by apostvav** [comment]
Good, if you have any issues let me know.
About the grafana dashboards, unfortunately I haven't done anything on that.
