### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by sanderkukk** [apostvav/kannel_exporter#9]
Hi, trying to run the exporter. This will output error.

```  
Traceback (most recent call last):
  File "kannel_exporter.py", line 405, in <module>
    main()
  File "kannel_exporter.py", line 397, in main
    REGISTRY.register(KannelCollector(args.target, status_password, opts))
  File "/usr/local/lib/python3.4/dist-packages/prometheus_client/registry.py", line 24, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.4/dist-packages/prometheus_client/registry.py", line 64, in _get_names
    for metric in desc_func():
  File "kannel_exporter.py", line 319, in collect
    response['gateway']['smscs']['smsc'])
  File "kannel_exporter.py", line 250, in _collect_smsc_stats
    + int(smsc['received']['sms']))
TypeError: string indices must be integers

```

And the xml.

```
<?xml version="1.0"?>
<gateway>
<version>Kannel bearerbox version `1.4.3'.
Build `Nov 24 2011 09:54:00', compiler `4.6.2'.
System Linux, release 3.19.0-25-generic, version #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015, machine x86_64.
Hostname ######## IP 127.0.0.1.
Libxml version 2.7.8.
Using OpenSSL 1.0.0e 6 Sep 2011.
Compiled with MySQL 5.5.17, using MySQL 5.5.62.
Using SQLite 3.7.9.
Using native malloc.
</version>
<status>running, uptime 0d 11h 45m 39s</status>
	<wdp>
		<received><total>0</total><queued>0</queued></received>
		<sent><total>0</total><queued>0</queued></sent>
	</wdp>
	<sms>
		<received><total>1464</total><queued>1</queued></received>
		<sent><total>721</total><queued>0</queued></sent>
		<storesize>1</storesize>
		<inbound>1.28,0.06,0.03</inbound>
		<outbound>0.66,0.02,0.02</outbound>
	</sms>
	<dlr>
		<queued>519</queued>
		<storage>mysql</storage>
	</dlr>
<boxes>
	<box>
		<type>smsbox</type>
		<id>KANNELCLIENT</id>
		<IP>127.0.0.1</IP>
		<queue>0</queue>
		<status>on-line 0d 11h 44m 39s</status>
		<ssl>no</ssl>
	</box></boxes>
<smscs><count>11</count>
	<smsc>
		<name>SMPP:####:#######:CMT</name>
		<id>#####</id>
		<status>online 42339s</status>
		<received>33</received>
		<sent>17</sent>
		<failed>0</failed>
		<queued>0</queued>
	</smsc>
<smsc>
......
```

Sidenote what is the query for getting info from `<inbound>1.28,0.06,0.03</inbound>
		<outbound>0.66,0.02,0.02</outbound`

**Comment by sanderkukk** [comment]
I belive it is because Im using 1.4.3 and the smsc format is different?

**Comment by apostvav** [comment]
Hi,

Yes, you are right. It seems version 1.4.3, uses a different format for the smsc stats. From the sample you provided, I don't see any reference whether the sent/failed messages are SMS or DLRs. 

So, from the sample you provided, are the sent/failed messages supposed to be SMS? If so, what about DLRs?

On later versions, the format looks like that:
```
<sms>
    <received>0</received>
    <sent>0</sent>
    <inbound>0.00,0.00,0.00</inbound>
    <outbound>0.00,0.00,0.00</outbound>
</sms>
<dlr>
    <received>4</received>
    <sent>0</sent>
    <inbound>0.00,0.00,0.00</inbound>
    <outbound>0.00,0.00,0.00</outbound>
</dlr>
```

Concerning the inbound and outbound rate, those values are not exposed by the exporter. The reason is that for custom collectors, it is not recommended to export any rate metrics. You can use the rate() function to calculate rates over any period you like.

**Comment by sanderkukk** [comment]
Yes this is the complete xml. I just redacted couple of `<smsc></smsc>` tags. I guess newer versions start to give information per smsc connection. Maybe better idea is to update my kannel version and try again.
Thanks!
